all:
  hosts:
    localhost:
      connection: local
      ansible_python_interpreter: "{{ lookup('ansible.builtin.pipe', 'which python3') }}"
    couchdb:
      ansible_host: lenovo
      ansible_python_interpreter: /usr/bin/python3
      chttpd_port: 15984
      chttpd_bind_address: 0.0.0.0
